package com.HRMS.QuickDines.Recruitment.Entity;

public enum ApprovalModule {

    JOB_OPENING,
    JOB_DESCRIPTION,
    EMPLOYEE_RECRUITMENT,
    INTERVIEW_SELECTION,
    OFFER_LETTER,
    EMPLOYEE_ONBOARDING,
    PROBATION_CONFIRMATION,
    SALARY_STRUCTURE
}